# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9823519b1e87745e8e1efd6311f655e60dbc4a72f31d030440ef17c911f18de81918fc2047451d0439ffba4eb7807d8c569b30f4262f7e0dce4dd40f667c253d
  facebook_key: "259832444480401"
  facebook_secret: "2b4c47be979d580c97319e2bc111255d"

test:
  secret_key_base: 7e1e5d5c2d27c9c34025192a596f1ca070a96823a190e508f8804265b25712bfb48d64f17425b65c0e894165c9a10a4988c309cb4e5c1fcafb0653dc05327070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
